### ISSUE TITLE
0.3.0-alpha2 Starts searching - gets white screen

### ISSUE THREAD

**Issue by stan-qaz** [pascalopitz/unoffical-sonos-controller-for-linux#169]
Trying 0.3.0-alpha2 on both Arm v7 Appimage and the x64 RPM I get the same issue.

Spends more than 10 minutes searching then goes to a white screen. The menu bar still appears and seems to be working.

Developer tools shows a disconnected message, asks for a refresh. Doing so returns the searching screen.

After several more minutes the player screen appears. Tried grouping, adding a system took several minutes to happen after the save button was clicked.

The only thing that is different from my usual use is that I have a large 1034 songs, Christmas play list loaded from my local library. Clearing the queue from my Android controller doesn't seem to make a difference  in loading though.

Arm Developer Console is empty, the x86 one had this message:

```
Uncaught (in promise) Error: No device found
    at DeviceDiscovery.<anonymous> (/opt/sonos-controller-unofficial/resources/app.asar/node_modules/sonos/lib/asyncDeviceDiscovery.js:18:16)
    at Object.onceWrapper (node:events:513:28)
    at DeviceDiscovery.emit (node:events:406:35)
    at /opt/sonos-controller-unofficial/resources/app.asar/node_modules/sonos/lib/deviceDiscovery.js:66:14
```
x86 command line

stan@hp-800:~> /opt/sonos-controller-unofficial/sonos-controller-unofficial
[22278:1219/211416.287362:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

Arm command line

pi@pi-3bp-2:~/bin $ sonos-controller-unofficial-0.3.0-alpha2-armv7l.AppImage
[20970:1219/212230.133934:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[21008:1219/212231.047754:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by pascalopitz** [comment]
What happens if you add the IP manually?

**Comment by stan-qaz** [comment]
Not sure what that option does so I added my computer's IP with no change, and after a restart I tried one of my Sonos player's IP.

Adding the Sonos Beam's IP the controller started in about 13 seconds, about what it takes my Android controllers to start.

**Comment by EpicTMC** [comment]
have you opened up udp ports inbound on your machine from the sonos devices?

**Comment by stan-qaz** [comment]
> have you opened up udp ports inbound on your machine from the sonos devices?

I don't think I have a firewall running on my desktop openSuse Linux box or on my Pi. If this isn't only related to firewall issues I have no clue where to do it.

**Comment by stan-qaz** [comment]
For Alpha 3 I tried clearing all my Sonos devices queues and streaming sources to see if that made a difference. With no music the searching stays up for 4 to 5 minutes on my Pi 3 system before the screen goes to showing my system.

Command line: ~/bin $ sonos-controller-unofficial-0.3.0-alpha3-armv7l.AppImage
```
[31072:1231/132255.570530:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[31109:1231/132256.599236:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[31082:1231/132259.308386:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```
Console log:
[-1640982873453.log](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/7797015/-1640982873453.log)

**Comment by pascalopitz** [comment]
Not sure what could cause this. The step from 0.2.x to 0.3.0-alpha is
basically updating to the latest electron version, and this moving things
around a bit since the renderer process doesn't have access to nodejs APIs
anymore.

I'm happy to keep building the binaries for ARM with electron builder, but
personally it's not my use case and I won't spend significant time
re-creating a raspberry pi environment or similar. Happy to accept pull
requests though.

My first angle of attack would be to have a look into what exactly changed
in Electron in terms of ARM support.
