### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by cass00** [pascalopitz/unoffical-sonos-controller-for-linux#22]
Compilation fails on Fedora. npm version 1.3.6
Error:

```
> sonos-controller-unofficial@0.0.10 postinstall unoffical-sonos-controller-for-linux
> install-app-deps


unoffical-sonos-controller-for-linux/node_modules/electron-builder/out/cli/install-app-deps.js:16
let main = (() => {
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0

```

**Comment by pascalopitz** [comment]
Can't replicate
